// GENERATED FILE. Do not edit by hand.
//
// Regenerated by scripts/src/sync-insights.ts from each product's blog
// registry. Run `pnpm --filter @workspace/scripts run sync-insights` after a
// product publishes, or let the weekly job do it.
//
// Aggregated writing from across the product suite. EdenNX does not publish its
// own posts: every entry links out to the product site that wrote it, so the
// canonical URL stays with the product and nothing is duplicated across domains.
// Titles, standfirsts, dates, tags, and read times are copied verbatim.

export type InsightSource = "EdenRadar" | "EdenCompliance";

export type Insight = {
  source: InsightSource;
  title: string;
  /** The standfirst if the post has one, else its card description. */
  lede: string;
  /** ISO date, drives newest-first order. */
  date: string;
  tag: string;
  readTime: string;
  url: string;
};

const ER = "https://edenradar.com/blog";
const EC = "https://edencompliance.com/blog";

export const INSIGHTS: Insight[] = [
  {
    source: "EdenCompliance",
    title: "EdenCompliance is live.",
    lede: "Vendor quality, audits, and a two-way vendor portal on one controlled record.",
    date: "2026-08-12",
    tag: "Announcement",
    readTime: "4 min read",
    url: `${EC}/edencompliance-is-live`,
  },
  {
    source: "EdenCompliance",
    title: "What we mean by a controlled record",
    lede: "Nothing is deleted, everything is attributable, and the history is checkable. Here is what each of those actually means.",
    date: "2026-08-12",
    tag: "Platform",
    readTime: "5 min read",
    url: `${EC}/what-we-mean-by-a-controlled-record`,
  },
  {
    source: "EdenRadar",
    title: "What 34,186 academic assets are actually made of",
    lede: "Diagnostics and devices outnumber small molecules and antibodies. The field talks about the other half.",
    date: "2026-08-12",
    tag: "Data",
    readTime: "4 min read",
    url: `${ER}/what-the-index-is-made-of`,
  },
  {
    source: "EdenRadar",
    title: "Where the other 71 percent of the index sits",
    lede: "A third of the index sits beyond the fifty largest offices, and a tenth of it is federal.",
    date: "2026-08-12",
    tag: "Data",
    readTime: "4 min read",
    url: `${ER}/outside-the-top-tier`,
  },
  {
    source: "EdenCompliance",
    title: "Noticing the cause",
    lede: "Interval-based scheduling is the right backbone. It is also indifferent to news.",
    date: "2026-08-10",
    tag: "Practice",
    readTime: "5 min read",
    url: `${EC}/for-cause-triggers`,
  },
  {
    source: "EdenCompliance",
    title: "Two questions",
    lede: "Nobody asks to see your software. They ask what the list said in March, and who signed it.",
    date: "2026-08-07",
    tag: "Explainer",
    readTime: "5 min read",
    url: `${EC}/two-questions`,
  },
  {
    source: "EdenCompliance",
    title: "Nobody's job",
    lede: "Requalification does not lapse through carelessness. It lapses because the chasing has no owner.",
    date: "2026-08-05",
    tag: "Practice",
    readTime: "4 min read",
    url: `${EC}/nobodys-job`,
  },
  {
    source: "EdenRadar",
    title: "What the fit score is comparing",
    lede: "A ranked list makes a claim tens of thousands of times a day. Here is what stands behind it.",
    date: "2026-08-05",
    tag: "Product",
    readTime: "3 min read",
    url: `${ER}/what-the-fit-score-does-not-know`,
  },
  {
    source: "EdenCompliance",
    title: "What a spreadsheet cannot do",
    lede: "A workbook holds the current state perfectly well. That is not the part that fails.",
    date: "2026-08-03",
    tag: "Perspective",
    readTime: "4 min read",
    url: `${EC}/what-a-spreadsheet-cannot-do`,
  },
  {
    source: "EdenRadar",
    title: "One office's preclinical is another's discovery",
    lede: "Stage is one of the first fields people filter on, and the one that most rewards normalizing.",
    date: "2026-07-30",
    tag: "Explainer",
    readTime: "4 min read",
    url: `${ER}/stage-language-is-not-standard`,
  },
  {
    source: "EdenRadar",
    title: "What a tech transfer office is actually optimizing for",
    lede: "A licensing office runs on a scoreboard of its own, and reading it wins deals a term sheet alone will not.",
    date: "2026-07-17",
    tag: "Explainer",
    readTime: "5 min read",
    url: `${ER}/what-a-tto-optimizes-for`,
  },
  {
    source: "EdenRadar",
    title: "Four places an asset surfaces before the patent does",
    lede: "The eighteen-month patent lag is real. Four other records arrive well ahead of it.",
    date: "2026-07-06",
    tag: "Explainer",
    readTime: "5 min read",
    url: `${ER}/before-the-patent-publishes`,
  },
  {
    source: "EdenRadar",
    title: "What we mean by \"the index\"",
    lede: "A plain introduction to what EdenRadar actually measures: what a tech transfer office is, what counts as an asset, and why a live index beats a static one.",
    date: "2026-06-26",
    tag: "Data",
    readTime: "3 min read",
    url: `${ER}/what-we-mean-by-the-index`,
  },
  {
    source: "EdenRadar",
    title: "Why now",
    lede: "For decades, the gap between research and treatment was a structural fact you had to accept. It just became a solvable problem.",
    date: "2026-06-23",
    tag: "Perspective",
    readTime: "4 min read",
    url: `${ER}/why-now`,
  },
  {
    source: "EdenRadar",
    title: "EdenRadar is live.",
    lede: "See the full field before your first move.",
    date: "2026-06-22",
    tag: "Announcement",
    readTime: "4 min read",
    url: `${ER}/edenradar-is-live`,
  },
];

export const SORTED_INSIGHTS: Insight[] = [...INSIGHTS].sort((a, b) =>
  a.date < b.date ? 1 : a.date > b.date ? -1 : 0
);

export function countBySource(source: InsightSource): number {
  return INSIGHTS.filter((i) => i.source === source).length;
}

export function formatDate(iso: string): string {
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(Date.UTC(y, m - 1, d)).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    timeZone: "UTC",
  });
}
